title: "Krzysztof Hoffmann IT"
email: "krzysiekpl@gmail.com"
description: "Creating innovative Flutter applications."
baseurl: ""
url: "http://yourdomain.com"
twitter_username: "krzysztofhoffmann"
github_username:  "krzysztofhoffmann"
theme: jekyll-theme-cayman
